#!/bin/sh
set -e

cd ~/.vim_runtime

# Start writing to .vimrc
echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
' > ~/.vimrc

# Automatically source all vim files in the vimrcs directory
# find vimrcs -type f -name '*.vim' | sort | while read filename; do
#     echo "source ~/.vim_runtime/$filename" >> ~/.vimrc
# done
echo '' >> ~/.vimrc

find vimrcs4Extend -type f -name '*.vim' | sort | while read filename; do
    echo "source ~/.vim_runtime/$filename" >> ~/.vimrc
done

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"

# Copy .vimrc contents to .ideavimrc and add IntelliJ IDEA specific settings
cp ~/.vimrc ~/.ideavimrc

echo '
" IntelliJ IDEA specific settings' >> ~/.ideavimrc
find vimrcs4Jetbrains -type f -name '*.vim' | sort | while read filename; do
    echo $filename
    echo "source ~/.vim_runtime/$filename" >> ~/.ideavimrc
done

echo "Also configured the .ideavimrc for IntelliJ IDEA Vim plugin!"
