#!/bin/sh
set -e
append_sources() {
    local source_dir=$1
    local target_file=$2
    local base_dir=~/.vim_runtime

    find "${base_dir}/${source_dir}" \( -name '*.vim' -o -name '*.lua' \) | sort | while read filename; do
      echo "source $filename" >> "${target_file}"
    done
    echo '' >> "${target_file}"
}
cd ~/.vim_runtime

# Start writing to .vimrc
cat > ~/.vimrc <<EOF
" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
source ~/.vim_runtime/vimrcs/customize.vim

EOF

# append_sources "vimrcs" ~/.vimrc
append_sources "vimrcs4Extend" ~/.vimrc
echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"

# add config to .gvimrc
cp ~/.vimrc ~/.config/nvim/init.vim
#echo > "${HOME}/.config/nvim/init.lua"

echo "if exists(\"g:neovide\")" >> ~/.config/nvim/init.vim
  append_sources "vimrcs4NeoVide" ~/.config/nvim/init.vim
echo "endif" >> ~/.config/nvim/init.vim
echo "Configure for NeoVim"

cp ~/.vimrc ~/.ideavimrc
echo '
" IntelliJ IDEA specific settings' >> ~/.ideavimrc
append_sources "vimrcs4Jetbrains" ~/.ideavimrc
echo "Also configured the .ideavimrc for IntelliJ IDEA Vim plugin!"

